export const dataSimulation = [
  {
    id: 1,
    departure_city: "Paris",
    departure_date: "2023-04-10",
    price: 120,
    length: 10,
    width: 5,
    height: 3,
    type_of_marchandise: "Électronique",
    quantity: 3,
    destination_city: "Lyon",
  },
  {
    id: 2,
    departure_city: "Lyon",
    departure_date: "2023-04-12",
    price: 80,
    length: 8,
    width: 4,
    height: 2,
    type_of_marchandise: "Vêtements",
    quantity: 5,
    destination_city: "Marseille",
  },
  {
    id: 3,
    departure_city: "Marseille",
    departure_date: "2023-04-15",
    price: 200,
    length: 12,
    width: 6,
    height: 4,
    type_of_marchandise: "Meubles",
    quantity: 1,
    destination_city: "Toulouse",
  },
  {
    id: 4,
    departure_city: "Lille",
    departure_date: "2023-04-20",
    price: 150,
    length: 7,
    width: 3,
    height: 2,
    type_of_marchandise: "Informatique",
    quantity: 4,
    destination_city: "Nantes",
  },
  {
    id: 40,
    departure_city: "Nancy",
    departure_date: "2023-05-01",
    price: 80,
    length: 6,
    width: 3,
    height: 2,
    type_of_marchandise: "Vêtements",
    quantity: 2,
    destination_city: "Metz",
  },
  {
    id: 42,
    departure_city: "Strasbourg",
    departure_date: "2023-05-05",
    price: 120,
    length: 9,
    width: 5,
    height: 3,
    type_of_marchandise: "Produits de beauté",
    quantity: 1,
    destination_city: "Colmar",
  },
  {
    id: 49,
    departure_city: "Lyon",
    departure_date: "2023-05-12",
    price: 90,
    length: 6,
    width: 4,
    height: 2,
    type_of_marchandise: "Textiles",
    quantity: 3,
    destination_city: "Grenoble",
  },
  {
    id: 43,
    departure_city: "Marseille",
    departure_date: "2023-05-15",
    price: 200,
    length: 12,
    width: 6,
    height: 4,
    type_of_marchandise: "Meubles",
    quantity: 1,
    destination_city: "Toulouse",
  },
  {
    id: 50,
    departure_city: "Nice",
    departure_date: "2023-06-01",
    price: 180,
    length: 9,
    width: 5,
    height: 3,
    type_of_marchandise: "Produits frais",
    quantity: 2,
    destination_city: "Bordeaux",
  },
  {
    id: 56,
    departure_city: "Lille",
    departure_date: "2023-06-05",
    price: 130,
    length: 8,
    width: 3,
    height: 2,
    type_of_marchandise: "Bijoux",
    quantity: 3,
    destination_city: "Nîmes",
  },
  {
    id: 52,
    departure_city: "Rennes",
    departure_date: "2023-06-08",
    price: 150,
    length: 7,
    width: 4,
    height: 2,
    type_of_marchandise: "Vêtements",
    quantity: 4,
    destination_city: "Nantes",
  },
  {
    id: 58,
    departure_city: "Toulouse",
    departure_date: "2023-06-12",
    price: 80,
    length: 6,
    width: 4,
    height: 2,
    type_of_marchandise: "Textiles",
    quantity: 6,
    destination_city: "Montpellier",
  },
  {
    id: 51,
    departure_city: "Bordeaux",
    departure_date: "2023-06-15",
    price: 200,
    length: 12,
    width: 6,
    height: 4,
    type_of_marchandise: "Meubles",
    quantity: 1,
    destination_city: "Toulouse",
  },
  {
    id: 59,
    departure_city: "Lyon",
    departure_date: "2023-06-18",
    price: 120,
    length: 10,
    width: 5,
    height: 3,
    type_of_marchandise: "Électronique",
    quantity: 3,
    destination_city: "Lille",
  },
  {
    id: 53,
    departure_city: "Nantes",
    departure_date: "2023-06-22",
    price: 110,
    length: 5,
    width: 3,
    height: 2,
    type_of_marchandise: "Jouets",
    quantity: 4,
    destination_city: "Brest",
  },
  {
    id: 54,
    departure_city: "Marseille",
    departure_date: "2023-06-25",
    price: 210,
    length: 11,
    width: 7,
    height: 4,
    type_of_marchandise: "Produits cosmétiques",
    quantity: 1,
    destination_city: "Rennes",
  },
  {
    id: 55,
    departure_city: "Lyon",
    departure_date: "2023-06-28",
    price: 80,
    length: 6,
    width: 3,
    height: 2,
    type_of_marchandise: "Informatique",
    quantity: 2,
    destination_city: "Metz",
  },
];
