export const connexionDatas = [
  {
    text: "Nom",
    placeholder: "Nom",
    name: "name",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Prénom",
    placeholder: "Prénom",
    name: "firstname",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Date de naissance",
    name: "birth",
    type: "date",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Téléphone",
    name: "phone",
    type: "tel",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Adresse",
    placeholder: "Adresse",
    name: "address",
    type: "text",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Complément d'adresse",
    placeholder: "Adresse2",
    name: "address2",
    type: "text",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Ville",
    placeholder: "Ville",
    name: "town",
    type: "text",
    maxWidth: "16rem",
    required: true,
  },
  {
    text: "Code postal",
    placeholder: "Code postal",
    name: "postalCode",
    type: "text",
    maxWidth: "16rem",
    required: true,
  },
];
